### ISSUE TITLE
jfes.c issues part 2

### ISSUE THREAD

**Issue by f2404** [NeonMercury/jfes#3]
1. return jfes_memcmp(data, "null", 4) == 0;
   Better use strlen("null") instead of magic numbers.
2. jfes_is_integer():
   a. what about hexadecimal integers?
   b. why are you casting '0' and '9' from char to int? data[i] is char.
3. jfes_is_double():
   a. same question about casting;
   b. you don't need to use "else if" if the if block ends with "continue".
4. jfes_string_to_integer() and jfes_string_to_double() just ignore non-number characters in input - is this the intended behavior?
5. char *jfes_boolean_to_string(int value) {
   static char *true_value = "true";
   static char *false_value = "false";
   return value ? true_value : false_value;
   }
   Just 'return value ? "true" : "false";'
   Maybe it's worth to have defines for "true" and "false" to use them in such functions.

**Comment by f2404** [comment]
I'm tired, need a break ;)

**Comment by dmitrii-eremin** [comment]
Thank you very much for these valuable reports! 
1. I will make this argument optional, as I described in [this](https://github.com/NeonMercury/jfes/issues/2#issuecomment-150780199) comment.
2. All accepted. I'll work on hexadecimal and octal integers.
3. Casting accepted. But I think I need to use `else if`, because this condition does not interfere with the course of the program, does not affect the performance, but shows a program algorithm.
4. These functions returns an integer/floating point value. They can't signal, if input data is invalid. I think, I'll add to the functions description warning, that input data should be checked for correct input by `jfes_is_integer()` and `jfes_is_double()` functions.
5. Accepted.

**Comment by f2404** [comment]
You're welcome :)

**Comment by f2404** [comment]
Also, I'd recommend splitting jfes.c into several modules - unless there are some very good reasons to keep all code in a single file.

**Comment by dmitrii-eremin** [comment]
JFES planned as single-file library, but it had grown. I will think about splitting it into several files, thank you.
